# Generated by Django 4.2 on 2025-12-04 15:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('correc1', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='production',
            name='batch',
        ),
        migrations.RemoveField(
            model_name='production',
            name='date',
        ),
        migrations.RemoveField(
            model_name='production',
            name='line',
        ),
        migrations.RemoveField(
            model_name='production',
            name='operator',
        ),
        migrations.AddField(
            model_name='production',
            name='profit',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='production',
            name='quantity_returned',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='production',
            name='quantity_sent',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='production',
            name='revenue',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='production',
            name='sale_price_per_kg',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='production',
            name='formule_name',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='productioningredient',
            name='cost',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='productioningredient',
            name='kg',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='productioningredient',
            name='name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='productioningredient',
            name='price',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='productioningredient',
            name='production',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ingredients', to='correc1.production'),
        ),
    ]
