# Generated by Django 4.2 on 2025-12-05 12:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('correc1', '0002_remove_production_batch_remove_production_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productioningredient',
            name='name',
            field=models.CharField(max_length=200),
        ),
    ]
