# Generated by Django 4.2 on 2025-12-03 12:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Production',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('formule_name', models.CharField(blank=True, max_length=200)),
                ('total_kg', models.FloatField(default=0.0)),
                ('batch', models.CharField(blank=True, max_length=50)),
                ('line', models.CharField(blank=True, max_length=50)),
                ('operator', models.CharField(blank=True, max_length=100)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('total_materials', models.FloatField(default=0.0)),
                ('labor_cost', models.FloatField(default=0.0)),
                ('energy_cost', models.FloatField(default=0.0)),
                ('packaging_cost', models.FloatField(default=0.0)),
                ('overhead_percent', models.FloatField(default=0.0)),
                ('overhead_cost', models.FloatField(default=0.0)),
                ('cogs_total', models.FloatField(default=0.0)),
                ('cost_per_kg', models.FloatField(default=0.0)),
                ('margin_percent', models.FloatField(default=0.0)),
                ('price_per_kg', models.FloatField(default=0.0)),
                ('price_total', models.FloatField(default=0.0)),
            ],
        ),
        migrations.CreateModel(
            name='Recipe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('total_demande_default', models.FloatField(default=100.0)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='ProductionIngredient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('percent', models.FloatField()),
                ('kg', models.FloatField()),
                ('price', models.FloatField()),
                ('cost', models.FloatField()),
                ('production', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='production_ingredients', to='cogsapp.production')),
            ],
        ),
        migrations.AddField(
            model_name='production',
            name='formule',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='cogsapp.recipe'),
        ),
        migrations.CreateModel(
            name='Ingredient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('percent', models.FloatField()),
                ('price', models.FloatField(help_text='Prix par kg')),
                ('recipe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ingredients', to='cogsapp.recipe')),
            ],
            options={
                'ordering': ('id',),
            },
        ),
    ]
