# Generated by Django 4.2 on 2025-12-04 13:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cogsapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='production',
            name='kg_acheter',
            field=models.FloatField(default=0.0, help_text='Kg achetés pour la production'),
        ),
        migrations.AddField(
            model_name='production',
            name='kg_presse',
            field=models.FloatField(default=0.0, help_text='Kg envoyés à la presse'),
        ),
        migrations.AddField(
            model_name='production',
            name='kg_retour',
            field=models.FloatField(default=0.0, help_text='Kg retournés après production'),
        ),
        migrations.AlterField(
            model_name='ingredient',
            name='percent',
            field=models.FloatField(help_text='Pourcentage dans la recette'),
        ),
        migrations.AlterField(
            model_name='production',
            name='overhead_percent',
            field=models.FloatField(default=0.0, help_text='Pourcentage des frais généraux'),
        ),
        migrations.AlterField(
            model_name='production',
            name='total_kg',
            field=models.FloatField(default=0.0, help_text='Quantité totale de production prévue (kg)'),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='total_demande_default',
            field=models.FloatField(default=100.0, help_text='Quantité totale par défaut (kg)'),
        ),
    ]
