# Generated by Django 4.2 on 2025-11-30 04:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Formule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('cout', models.FloatField(default=0.0)),
                ('profit', models.FloatField(default=0.0)),
                ('cogs', models.FloatField(default=0.0)),
                ('projection', models.FloatField(default=0.0)),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
