# Generated by Django 4.2 on 2025-11-30 13:44

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='formule',
            options={'ordering': ['-date_creation'], 'verbose_name': 'Formule', 'verbose_name_plural': 'Formules'},
        ),
        migrations.AddField(
            model_name='formule',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Mis à jour le'),
        ),
        migrations.AlterField(
            model_name='formule',
            name='cogs',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10, verbose_name='COGS'),
        ),
        migrations.AlterField(
            model_name='formule',
            name='cout',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10, verbose_name='Coût total'),
        ),
        migrations.AlterField(
            model_name='formule',
            name='date_creation',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Créé le'),
        ),
        migrations.AlterField(
            model_name='formule',
            name='description',
            field=models.TextField(blank=True, verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='formule',
            name='nom',
            field=models.CharField(max_length=200, verbose_name='Nom de la formule'),
        ),
        migrations.AlterField(
            model_name='formule',
            name='profit',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10, verbose_name='Profit'),
        ),
        migrations.AlterField(
            model_name='formule',
            name='projection',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10, verbose_name='Projection'),
        ),
    ]
