# Generated by Django 4.2 on 2025-11-30 13:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0002_alter_formule_options_formule_updated_at_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='formule',
            options={'verbose_name': 'Formule', 'verbose_name_plural': 'Formules'},
        ),
        migrations.RemoveField(
            model_name='formule',
            name='updated_at',
        ),
        migrations.AlterField(
            model_name='formule',
            name='cogs',
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name='formule',
            name='cout',
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name='formule',
            name='date_creation',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='formule',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='formule',
            name='nom',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='formule',
            name='profit',
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name='formule',
            name='projection',
            field=models.FloatField(default=0.0),
        ),
    ]
