# Generated by Django 4.2 on 2025-11-30 14:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0003_alter_formule_options_remove_formule_updated_at_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Composant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=200)),
                ('pourcentage', models.FloatField()),
                ('prix', models.FloatField()),
                ('formule', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='composants', to='finance.formule')),
            ],
            options={
                'verbose_name': 'Composant',
                'verbose_name_plural': 'Composants',
            },
        ),
    ]
