# Generated by Django 4.2 on 2025-11-30 18:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0004_composant'),
    ]

    operations = [
        migrations.RenameField(
            model_name='formule',
            old_name='cout',
            new_name='cout_par_kg',
        ),
        migrations.AddField(
            model_name='composant',
            name='cout_total',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='composant',
            name='kg',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='formule',
            name='cout_total',
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name='composant',
            name='pourcentage',
            field=models.FloatField(help_text='Pourcentage (%) du mélange'),
        ),
        migrations.AlterField(
            model_name='composant',
            name='prix',
            field=models.FloatField(help_text='Prix par kg'),
        ),
    ]
