# Generated by Django 4.2 on 2025-11-30 21:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0005_rename_cout_formule_cout_par_kg_composant_cout_total_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='composant',
            options={},
        ),
        migrations.AlterModelOptions(
            name='formule',
            options={},
        ),
        migrations.AddField(
            model_name='formule',
            name='total_demande',
            field=models.FloatField(default=100.0),
        ),
        migrations.AlterField(
            model_name='composant',
            name='pourcentage',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='composant',
            name='prix',
            field=models.FloatField(),
        ),
    ]
