# Generated by Django 4.2 on 2025-11-30 22:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0006_alter_composant_options_alter_formule_options_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='formule',
            old_name='projection',
            new_name='autres',
        ),
        migrations.AddField(
            model_name='formule',
            name='main_oeuvre',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='formule',
            name='prix_unitaire',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='formule',
            name='projection_annuelle',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='formule',
            name='projection_mensuelle',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='formule',
            name='transport',
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name='composant',
            name='pourcentage',
            field=models.FloatField(help_text='Pourcentage (%) du mélange'),
        ),
        migrations.AlterField(
            model_name='composant',
            name='prix',
            field=models.FloatField(help_text='Prix par kg'),
        ),
    ]
