# Generated by Django 4.2 on 2025-12-14 01:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cout',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=50)),
                ('quantite', models.FloatField()),
                ('prix_unitaire', models.FloatField()),
                ('total', models.FloatField()),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
